name: Execute workflow event

on:
  workflow_dispatch:
    

jobs:

  create_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.0

      - name: Simulate a build
        run: echo 'dummy build' > output.txt

      - name: Upload a build artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: 'test-artifact'
          path: 'output.txt'
